name: tool_mobile
description: Flutter Tools' base plus mobile. Use to create command line tools.
version: 1.9.5+1
homepage: https://github.com/mmcc007/tool_mobile
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  tool_base:
    git: https://github.com/ventskus-roman/tool_base

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.16.5
  mockito: 4.1.4